### ISSUE TITLE
Feature request: allow custom templates

### ISSUE THREAD

**Issue by janbiasi** [tancredi/fantasticon#12]
First off thanks for providing such a great library! 😸 It works great and does the job pretty solid.
One thing which would be great is to enable an option to provide custom HBS templates (at least for the CSS part).
There's a simple use case for SASS users, if we want to create additional SCSS variables for the icons for eg. using it in a custom `::after` selector we need to copy the `content: ''` attribute manually but a variable (eg. `$icon-<dashed-name>`) would be way easier to use.

Eventually providing more details about the icons in the callback `results` would also provide a great option to add more custom scripts without too much regex action.

Let me know what you think about these ideas :)

**Comment by tancredi** [comment]
Hi @janbiasi - I'm both planning to add off-the-shelf SCSS/SASS templates (they would be optional and require the user specifying asset types manually) - and add the ability of using custom generators (maybe both from npm modules and local scripts) although both features depend on available time for this project, and can't promise a time frame (SCSS/SASS should be really simple so hopefully sooner).

Regarding codepoints, I've just published version `1.0.13` which will return the codepoints used in the generator output, so you can in the meantime render your own SCSS template by just using the JS API.

Hope that helps - I'll keep the issue open as a reminder.

Also, if you'd like to contribute, you could open a PR for SASS/SCSS (I'd say let's have both syntaxes). You can find the generators logic in `src/generators/asset-types` and their templates under `templates`.

Obviously not expected but absolutely welcome :)

Hope this help

**Comment by janbiasi** [comment]
@tancredi thanks a lot for the positive feedback, I'm really looking forward to try `1.0.13` asap. and if I have some spare time this week or weekend I'd like to start working on the said PR for sure 😸!

**Comment by casaper** [comment]
@janbiasi @tancredi  I addressed this issue in #18 and also provide an extensive default scss template.

see #18 which builds on top of #17 so think away all but the last commit

**Comment by tancredi** [comment]
OK folks firstly thank you so much for the contributions :)

So, this got a bit messy as I've addressed PRs individually and there seemed to be a bit of duplication between the two.

@casaper your PR is still outstanding and after merging most of the changes from @janbiasi I've sorta created a bunch of merge conflicts.

Meanwhile, @casaper , I've merged your changes for better typing of asset type options.

I've included a bunch of other minor changes and fixes to both PRs - and as mentioned, did not add the custom template options for the command line utility as I wanted to keep granular options limited to config file / JS API - which is still open for discussion, I was just trying to get the basic features in first.

@casaper, is there anything from the PR that is missing in the currently merged implementation?

Apologies if I'm making a bit of confusion, limited time and lots to do on this :)

**Comment by tancredi** [comment]
Oh - find all new things on version 1.0.16

**Comment by casaper** [comment]
@tancredi 

> Apologies if I'm making a bit of confusion, limited time and lots to do on this :)

No Worries. I was fully aware that there will be incompatibilities with what @janbiasi did in #20. 

But that's fine. Now that it is merged I will see If I still have anything to add, to what @janbiasi  did.

I basically need to make it compatible with what I already started using in a project using my dirty temporary package [fantasticon-cas](https://www.npmjs.com/package/fantasticon-cas).

But I think that this won't be a big deal... Expect another PR in some Time and you will see. I'll close #18 now, since it is anyway not mergeable as is.

**Comment by janbiasi** [comment]
@casaper really awesome changes, thanks a lot! 🥳 One thing I noticed lately was that if a dev uses JS-in-TS (`// @ts-check` directive) it will complain in the fontTypes and assetTypes options as `enum`s aren't valid with the TS directive. 

Should we just ignore that as "known limitation", because making these types compatible would mean that we'd need to change the `enum` to `type`s and `const`s to keep the current type logic, what do you think @casaper & @tancredi ?

**Comment by casaper** [comment]
@janbiasi 

> Should we just ignore that as "known limitation", because making these types compatible would mean that we'd need to change the enum to types and consts to keep the current type logic, what do you think

Yeah, you're right, I also noticed it not being fully as it should be there.
I did it like this because otherwise It would have required quite some refactoring in the default options thing.
I think in general I agree with you, probably the Enums are not the best to go with any more. Rather literal string types in order to improve usability and just plain old constants for looping with the available options.

**Comment by janbiasi** [comment]
@casaper literal string types + constants for looping would also be the way I'd go, maybe we should open another feature request for that case, I will close this issue as the requested feature is now available :)

**Comment by casaper** [comment]
@janbiasi perhaps tomorrow I might have some spare time to make a little pr regarding this

**Comment by casaper** [comment]
@janbiasi  @tancredi 

I actually have an idea to structure the whole config file simpler, and I think it will be easier to use.

Instead of long explanations here, just wait for my PR. It will be like a proposal for a change in config object structure... Allot easier explained in code than in text here :wink:

**Comment by casaper** [comment]
@janbiasi || @tancredi 

I Think it would speed up things if you guys reviewed these PR's @ DefinitelyTyped:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49721
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49722
